#-------------------------------
# Site Settings
title: Michael Colella
description: A collection of projects and experiences from Michael Colella
logo: "/images/logo.svg"
logo_dark: "/images/logo-dark.svg"
color_scheme: light


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Portfolio"
      url: "/portfolio/"
    - title: "Work Experience"
      url: "/experience/"

#-------------------------------
# Footer Settings

# Footer Navigation
footer_menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Portfolio'
      url: '/portfolio/'
    - title: 'Work Experience'
      url: '/experience/' 

# Social Links
social:
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/in/michaelcolella/"}
- {icon: "fa-brands fa-github", name: "GitHub", link: "https://github.com/mcolella326"}
